import {
  Archive,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Banknote,
  Barcode,
  BookmarkCheck,
  Building2,
  CalendarClock,
  CalendarX,
  CircleCheck,
  CircleCheckBig,
  CircleDashed,
  CircleX,
  ClipboardList,
  Clock,
  CookingPot,
  CopyCheck,
  Eye,
  FileClock,
  FileEdit,
  Handshake,
  HeartHandshake,
  Hourglass,
  Laptop,
  Minus,
  MonitorCog,
  Smartphone,
  OctagonX,
  Package,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackageX,
  PauseCircle,
  ScanText,
  SearchX,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Sparkle,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Truck,
  Undo2,
  Upload,
  UserCheck,
  UserCog,
  UserSearch,
  Users,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/**
 * Explicit name -> component map for the icons named in @techpioasset/ui-tokens.
 *
 * Tokens carry icon *names* because the mobile app resolves them differently.
 * Importing the whole Lucide namespace to look one up would defeat tree-shaking,
 * so the mapping is explicit, and a unit test asserts every token name appears
 * here - a typo fails the build rather than rendering nothing at runtime.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Archive,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Banknote,
  Barcode,
  BookmarkCheck,
  Building2,
  CalendarClock,
  CalendarX,
  CircleCheck,
  CircleCheckBig,
  CircleDashed,
  CircleX,
  ClipboardList,
  Clock,
  CookingPot,
  CopyCheck,
  Eye,
  FileClock,
  FileEdit,
  Handshake,
  HeartHandshake,
  Hourglass,
  Laptop,
  Minus,
  MonitorCog,
  Smartphone,
  OctagonX,
  Package,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackageX,
  PauseCircle,
  ScanText,
  SearchX,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Sparkle,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Truck,
  Undo2,
  Upload,
  UserCheck,
  UserCog,
  UserSearch,
  Users,
  Wrench,
};

export function resolveIcon(name: string): LucideIcon | undefined {
  return ICON_REGISTRY[name];
}
